### PR TITLE
Fixed first strcpy test to check if copied string has NULL at end

### PR DESCRIPTION
**Pull request by whitewolf31**
The first strcpy test doesn't fail if we don't add a NULL terminator in the string. This is bad since people assume the function is correct and later down the road we end up pulling our hair with other tests that use our strcpy implementation. Should fail if no NULL character is added at the end

### CODE REVIEW

**Comment by razvand** [comment]
@whitewolf31, could you please elaborate this? It's not clear to me what the problem is. The correct wording should be `NUL` terminator character (`NULL` is a pointer).

**Comment by whitewolf31** [comment]
@razvand When implementing `strcpy`, if you don't add the `NUL` character, the current tests will pass, since the destination `char dst[128]` is not initialized. If we force `dst` to be initialized to a string with a length bigger than `src`, the test will fail if `strcpy` doesn't add the `NUL` character at the end.

Before Fix:
```
char src[] = "sticksandstones";
char dst[128];
strcpy(dst, src); // dst will be sticksandstones if no NUL character is added, but we can't know which character will be at the end. Can be NUL, can be anything else
strlen(src) == strlen(dst) // Might be true, might be false
```

After Fix:
```
char src[] = "sticksandstones";
char dst[128] = "maybreakyyourbones";
strcpy(dst, src); // dst will be sticksandstonesnes if no NUL character is added
strlen(src) == strlen(dst) // Will be false since they have different lenghts
``` 

This will prove problematic when implementing `strncat` which uses `strcpy` and doesn't forgive not adding NUL character at the end.

**Comment by razvand** [comment]
@whitewolf31, will look into that.

**Comment by razvand** [comment]
@whitewolf31, I updated the tests with [this commit](https://github.com/open-education-hub/operating-systems/pull/209/commits/0d578e10b175e1e32136f26d73bee2325e4deba2). I added you as co-author. See if that solves it. If so, close this PR.

**Pull request closed without merging**
